### ISSUE TITLE
Error using this library - ansible_collections module not found

### ISSUE THREAD

**Issue by AlanCoding** [ansible-community/pytest-ansible#97]
I noticed that when I upgraded Ansible-core I got errors from any fixtures that are running pytest-ansible commands. I did a git bisect and narrowed it down to breaking with this pull request:

https://github.com/ansible/ansible/pull/78915

```
________________________________________________ Test_Job.test_alan _________________________________________________
Traceback (most recent call last):
  File "/home/alancoding/repos/tower-qa/tests/api/jobs/test_jobs.py", line 178, in test_alan
    ansible_adhoc()['all'].file(path='/tmp/alan', state='absent')
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/pytest_ansible/module_dispatcher/v213.py", line 171, in _run
    tqm.run(play)
  File "/home/alancoding/repos/ansible/lib/ansible/executor/task_queue_manager.py", line 333, in run
    play_return = strategy.run(iterator, play_context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/ansible/lib/ansible/plugins/strategy/linear.py", line 193, in run
    action = action_loader.get(task_action, class_only=True, collection_list=task.collections)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/ansible/lib/ansible/plugins/loader.py", line 855, in get
    return self.get_with_context(name, *args, **kwargs).object
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/ansible/lib/ansible/plugins/loader.py", line 865, in get_with_context
    plugin_load_context = self.find_plugin_with_context(name, collection_list=collection_list)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/ansible/lib/ansible/plugins/loader.py", line 586, in find_plugin_with_context
    result = self._resolve_plugin_step(name, mod_type, ignore_deprecated, check_aliases, collection_list, plugin_load_context=plugin_load_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/ansible/lib/ansible/plugins/loader.py", line 682, in _resolve_plugin_step
    return self._find_plugin_legacy(name, plugin_load_context, ignore_deprecated, check_aliases, suffix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/ansible/lib/ansible/plugins/loader.py", line 787, in _find_plugin_legacy
    return self._find_fq_plugin(fq_name=candidate_fqcr, extension=suffix, plugin_load_context=plugin_load_context, ignore_deprecated=ignore_deprecated)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/ansible/lib/ansible/plugins/loader.py", line 476, in _find_fq_plugin
    routing_metadata = self._query_collection_routing_meta(acr, plugin_type, extension=extension)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/ansible/lib/ansible/plugins/loader.py", line 434, in _query_collection_routing_meta
    collection_pkg = import_module(acr.n_python_collection_package_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ansible_collections'
```

I couldn't find this particular error documented anywhere in this repo, so I wanted to go ahead and file it. Maybe it's related to the "v3" work? But I installed from the stable 2.x branch, and the bug is from a commit that went into ansible-core.

Ping @sivel, is there something obvious I missed?

**Comment by AlanCoding** [comment]
Confirming again here - I hit this when installing:

```
pip install git+https://github.com/ansible-community/pytest-ansible.git@stable/2.x
```

Last commit was Sept 2022, so I can link to the code:

https://github.com/ansible-community/pytest-ansible/blob/052d5a27ba61308385ed4e361cf91756ed9e8d93/pytest_ansible/module_dispatcher/v213.py#L171

The rest of the stack trace seems to be in Ansible-core.

**Comment by AlanCoding** [comment]
Put up proposed patch.

**Comment by ssbarnea** [comment]
Fixed on main branch, I will make a pre-release to make it easier to use by others.

**Comment by AlanCoding** [comment]
Thanks, link fix PR https://github.com/ansible-community/pytest-ansible/pull/103
